[tool.poetry]
name = "rdf-service"
version = "0.1.0"
description = ""
authors = ["Adam C. Saunders <saunders@cs.umass.edu>"]
readme = "README.md"
packages = [{include = "rdf_service"}]

[tool.poetry.dependencies]
python = "^3.11"
sparqlwrapper = "^2.0.0"
pytest = "^7.4.2"
pyright = "^1.1.329"
click = "^8.1.7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
